### PR TITLE
use pify over fs-promise

### PR DESCRIPTION
**Pull request by jamestalmage**
This allows nyc coverage to work

### CODE REVIEW

**Comment by thangngoc89** [comment]
Thanks for investigating on this. But I use `fs-promise` extensively. Using pify requires a lot of refactor in the codebase. I'll use fixture instead of mocking fs for this instead.

**Comment by thangngoc89** [comment]
Hum. After reconsider writing tests using fixture, it's really a pain. And it looks like using pify doesn't require a lot of changes.

**Comment by jamestalmage** [comment]
Up to you how to handle it in your codebase. I would still like to hunt down exactly why it doesn't work with `fs-promise`

**Comment by thangngoc89** [comment]
> I would still like to hunt down exactly why it doesn't work with `fs-promise`

Thanks

**Comment by jamestalmage** [comment]
cc: @novemberborn

**Comment by novemberborn** [comment]
Figured it out. `fs-promise` [uses](https://github.com/kevinbeaty/fs-promise/blob/4fa1d2d0d64f1c555302106b939c61b5a76ed75f/index.js#L3) `mz` which [tries to load](https://github.com/normalize/mz/blob/1704ccd4b630961deb437f79098cad0d46dd25ea/fs.js#L5) `graceful-fs`. Unfortunately `nyc` has a transitive dependency on `graceful-fs` as well. This means `fs-promise` ends up binding against the unmocked `graceful-fs`.

The `pify` approach here is late-binding against `fs.readFile`, thus it gets to use the actual mocked filesystem.

**Pull request closed without merging**
